---
# Demo: ImagePullBackOff scenario
# This HelmRelease deploys nginx with a non-existent image tag
# Result: Pod stuck in ImagePullBackOff, HelmRelease shows failed
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: demo-imagepull-fail
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: demo-apps
  chart:
    spec:
      chart: nginx
      version: ">=15.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      registry: docker.io
      repository: bitnami/nginx
      # Intentionally wrong tag - will cause ImagePullBackOff
      tag: "does-not-exist-v999"
