---
# Capacitor Next - self-hosted Flux UI (beta)
# Based on: https://github.com/gimlet-io/capacitor/tree/main/self-host/yaml/capacitor-next
# NOTE: Self-hosted mode is beta. For licensing contact laszlo@gimlet.io
#
# Access: http://<colima-ip>:30081 or kubectl port-forward svc/capacitor-next -n flux-system 9000:80

# --- ServiceAccount ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: capacitor-next
  namespace: flux-system
---
# --- RBAC: Impersonator (allows capacitor to impersonate SAs) ---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capacitor-next-impersonator
rules:
  - apiGroups: [""]
    resources: ["users", "groups", "serviceaccounts"]
    verbs: ["impersonate"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capacitor-next-impersonator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capacitor-next-impersonator
subjects:
  - kind: ServiceAccount
    name: capacitor-next
    namespace: flux-system
---
# --- RBAC: Preset clusteradmin SA (for noauth mode) ---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capacitor-next-preset-clusteradmin
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: capacitor-next-preset-clusteradmin
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capacitor-next-preset-clusteradmin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capacitor-next-preset-clusteradmin
subjects:
  - kind: ServiceAccount
    name: capacitor-next-preset-clusteradmin
    namespace: flux-system
---
# --- ConfigMap: noauth mode for local testing ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: capacitor-next
  namespace: flux-system
data:
  AUTH: "noauth"
  AUTH_DEBUG: "true"
  IMPERSONATE_SA_RULES: "noauth=flux-system:capacitor-next-preset-clusteradmin"
  FLUXCD_NAMESPACE: "flux-system"
---
# --- Secret: session keys + registry config ---
# NOTE: LICENSE_KEY is placeholder - contact laszlo@gimlet.io for real one
apiVersion: v1
kind: Secret
metadata:
  name: capacitor-next
  namespace: flux-system
type: Opaque
stringData:
  LICENSE_KEY: "trial-local-testing"
  SESSION_HASH_KEY: "base64:dGhpc2lzYXRlc3RoYXNoa2V5Zm9ybG9jYWx0ZXN0aW5n"
  SESSION_BLOCK_KEY: "base64:dGhpc2lzYXRlc3RibG9ja2tleWZvcmxvY2FsdGVzdA=="
  registry.yaml: |
    clusters:
    - id: in-cluster
      name: colima-local
      apiServerURL: https://kubernetes.default.svc
      certificateAuthorityFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      serviceAccount:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
---
# --- Deployment ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capacitor-next
  namespace: flux-system
  labels:
    app: capacitor-next
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capacitor-next
  template:
    metadata:
      labels:
        app: capacitor-next
    spec:
      serviceAccountName: capacitor-next
      containers:
        - name: capacitor-next
          image: ghcr.io/gimlet-io/capacitor-next:0.14.0-rc.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: capacitor-next
            - secretRef:
                name: capacitor-next
          volumeMounts:
            - name: registry
              mountPath: /app/backend/registry.yaml
              subPath: registry.yaml
      volumes:
        - name: registry
          secret:
            secretName: capacitor-next
            items:
              - key: registry.yaml
                path: registry.yaml
---
# --- Service (NodePort for local access) ---
apiVersion: v1
kind: Service
metadata:
  name: capacitor-next
  namespace: flux-system
  labels:
    app: capacitor-next
spec:
  type: NodePort
  selector:
    app: capacitor-next
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30081
