---
# Capacitor v0.4.8 - Simple Flux UI (last version before license-gated "Next")
# Source: https://github.com/gimlet-io/capacitor/tree/capacitor-v0.4.8/deploy/k8s
# Access: kubectl port-forward svc/capacitor -n flux-system 9000:9000
#         or http://<colima-ip>:30081

# --- ServiceAccount ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: capacitor
  namespace: flux-system
---
# --- RBAC ---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capacitor
rules:
  - apiGroups:
      - networking.k8s.io
      - apps
      - ""
    resources:
      - pods
      - pods/log
      - ingresses
      - deployments
      - services
      - secrets
      - events
      - configmaps
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - source.toolkit.fluxcd.io
      - kustomize.toolkit.fluxcd.io
      - helm.toolkit.fluxcd.io
      - infra.contrib.fluxcd.io
    resources:
      - gitrepositories
      - ocirepositories
      - buckets
      - helmrepositories
      - helmcharts
      - kustomizations
      - helmreleases
      - terraforms
    verbs:
      - get
      - watch
      - list
      - patch  # for force reconcile
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capacitor
subjects:
  - kind: ServiceAccount
    name: capacitor
    namespace: flux-system
roleRef:
  kind: ClusterRole
  name: capacitor
  apiGroup: rbac.authorization.k8s.io
---
# --- Service (NodePort for local access) ---
apiVersion: v1
kind: Service
metadata:
  name: capacitor
  namespace: flux-system
  labels:
    app.kubernetes.io/name: capacitor
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30081
  selector:
    app.kubernetes.io/name: capacitor
---
# --- Deployment ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capacitor
  namespace: flux-system
  labels:
    app.kubernetes.io/name: capacitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: capacitor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: capacitor
    spec:
      serviceAccountName: capacitor
      securityContext:
        fsGroup: 999
      containers:
        - name: capacitor
          image: ghcr.io/gimlet-io/capacitor:v0.4.8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 101
            runAsNonRoot: true
            runAsUser: 100
            seccompProfile:
              type: RuntimeDefault
