---
# Source: weave-gitops/templates/network-policy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dashboard-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: weave-gitops
      app.kubernetes.io/instance: weave-gitops
  ingress:
  - ports:
    - port: 9001
      protocol: TCP
  policyTypes:
  - Ingress
---
# Source: weave-gitops/templates/network-policy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dashboard-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: weave-gitops
      app.kubernetes.io/instance: weave-gitops
  egress:
    - {}
  policyTypes:
  - Egress
---
# Source: weave-gitops/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: weave-gitops
  labels:
    helm.sh/chart: weave-gitops-4.0.36
    app.kubernetes.io/name: weave-gitops
    app.kubernetes.io/instance: weave-gitops
    app.kubernetes.io/version: "v0.38.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: weave-gitops/templates/admin-user-creds.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cluster-user-auth
  namespace: flux-system
type: Opaque
data:
  username: "YWRtaW4="
  password: "JDJhJDEwJFAvdEhRMURORlhkdlgwelJHQThMUGVTT3liMEpYcTlyUDNmWjRXOEhHVHBMVjdxSERsV2hl"
---
# Source: weave-gitops/templates/admin-user-roles.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wego-admin-cluster-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: [ "get", "list", "watch" ]

  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: [ "buckets", "helmcharts", "gitrepositories", "helmrepositories", "ocirepositories" ]
    verbs: [ "get", "list", "watch", "patch" ]

  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: [ "kustomizations" ]
    verbs: [ "get", "list", "watch", "patch" ]

  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: [ "helmreleases" ]
    verbs: [ "get", "list", "watch", "patch" ]

  - apiGroups: [ "notification.toolkit.fluxcd.io" ]
    resources: [ "providers", "alerts" ]
    verbs: [ "get", "list", "watch" ]

  - apiGroups: ["infra.contrib.fluxcd.io"]
    resources: ["terraforms"]
    verbs: [ "get", "list", "watch", "patch" ]

  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["list", "watch"]

  - apiGroups: [ "notification.toolkit.fluxcd.io" ]
    resources: [ "providers", "alerts" ]
    verbs: [ "get", "list", "watch", "patch" ]
  
  - apiGroups: ["image.toolkit.fluxcd.io"]
    resources: [ "imagepolicies", "imagerepositories", "imageupdateautomations" ]
    verbs: [ "get", "list", "watch", "patch" ]
---
# Source: weave-gitops/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name:  weave-gitops
rules:
  # impersonation rules for ui calls
  - apiGroups: [""]
    resources: ["users","groups"]
    verbs: [ "impersonate" ]
  # Access to enterprise entitlement
  - apiGroups: [""]
    resources: [ "secrets" ]
    verbs: [ "get", "list" ]
    # or should return the first non-falsy result
    resourceNames: ["cluster-user-auth","oidc-auth"]

  # The service account needs to read namespaces to know where it can query
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "get", "list", "watch" ]

  # The service account needs to list custom resources to query if given feature
  # is available or not.
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: [ "list" ]
---
# Source: weave-gitops/templates/admin-user.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user-read-resources-cr
subjects:
- kind: User
  name: admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: wego-admin-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
# Source: weave-gitops/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  weave-gitops
  labels:
    helm.sh/chart: weave-gitops-4.0.36
    app.kubernetes.io/name: weave-gitops
    app.kubernetes.io/instance: weave-gitops
    app.kubernetes.io/version: "v0.38.0"
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: weave-gitops
    namespace: flux-system
roleRef:
  kind: ClusterRole
  name: weave-gitops
  apiGroup: rbac.authorization.k8s.io
---
# Source: weave-gitops/templates/admin-user-roles.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wego-admin-role
  namespace: flux-system
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: [ "get", "list", "watch" ]

  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: [ "buckets", "helmcharts", "gitrepositories", "helmrepositories", "ocirepositories" ]
    verbs: [ "get", "list", "watch", "patch" ]

  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: [ "kustomizations" ]
    verbs: [ "get", "list", "watch", "patch" ]

  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: [ "helmreleases" ]
    verbs: [ "get", "list", "watch", "patch" ]

  - apiGroups: [ "notification.toolkit.fluxcd.io" ]
    resources: [ "providers", "alerts" ]
    verbs: [ "get", "list", "watch", "patch" ]

  - apiGroups: ["infra.contrib.fluxcd.io"]
    resources: ["terraforms"]
    verbs: [ "get", "list", "watch", "patch" ]
---
# Source: weave-gitops/templates/admin-user.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-user-read-resources
  namespace: flux-system
subjects:
  - kind: User
    name: wego-admin
    namespace: flux-system
roleRef:
  kind: Role
  name: wego-admin-role
  apiGroup: rbac.authorization.k8s.io
---
# Source: weave-gitops/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: weave-gitops
  labels:
    helm.sh/chart: weave-gitops-4.0.36
    app.kubernetes.io/name: weave-gitops
    app.kubernetes.io/instance: weave-gitops
    app.kubernetes.io/version: "v0.38.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  type: NodePort
  ports:
    - port: 9001
      targetPort: http
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: weave-gitops
    app.kubernetes.io/instance: weave-gitops
---
# Source: weave-gitops/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weave-gitops
  labels:
    helm.sh/chart: weave-gitops-4.0.36
    app.kubernetes.io/name: weave-gitops
    app.kubernetes.io/instance: weave-gitops
    app.kubernetes.io/version: "v0.38.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: weave-gitops
    weave.works/app: weave-gitops-oss
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: weave-gitops
      app.kubernetes.io/instance: weave-gitops
  template:
    metadata:
      labels:
        app.kubernetes.io/name: weave-gitops
        app.kubernetes.io/instance: weave-gitops
        app.kubernetes.io/part-of: weave-gitops
        weave.works/app: weave-gitops-oss
    spec:
      serviceAccountName: weave-gitops
      containers:
        - name: weave-gitops
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          image: "ghcr.io/weaveworks/wego-app:v0.38.0"
          imagePullPolicy: IfNotPresent
          args:
            - "--log-level"
            - "info"
            - "--insecure"
          ports:
            - name: http
              containerPort: 9001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: WEAVE_GITOPS_FEATURE_TENANCY
              value: "true"
            - name: WEAVE_GITOPS_FEATURE_CLUSTER
              value: "false"
          resources:
            {}
