apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dashboard-ingress
  namespace: flux-system
spec:
  ingress:
  - ports:
    - port: 9001
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: weave-gitops
      app.kubernetes.io/name: weave-gitops
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dashboard-egress
  namespace: flux-system
spec:
  egress:
  - {}
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: weave-gitops
      app.kubernetes.io/name: weave-gitops
  policyTypes:
  - Egress
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: weave-gitops
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: weave-gitops
    app.kubernetes.io/version: v0.39.1-rc.1
    helm.sh/chart: weave-gitops-0.39.1-rc.1
  name: weave-gitops
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: weave-gitops
  namespace: flux-system
rules:
- apiGroups:
  - ''
  resources:
  - users
  - groups
  verbs:
  - impersonate
- apiGroups:
  - ''
  resourceNames:
  - cluster-user-auth
  - oidc-auth
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: weave-gitops
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: weave-gitops
    app.kubernetes.io/version: v0.39.1-rc.1
    helm.sh/chart: weave-gitops-0.39.1-rc.1
  name: weave-gitops
  namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: weave-gitops
subjects:
- kind: ServiceAccount
  name: weave-gitops
  namespace: flux-system
---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: weave-gitops
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: weave-gitops
    app.kubernetes.io/version: v0.39.1-rc.1
    helm.sh/chart: weave-gitops-0.39.1-rc.1
  name: weave-gitops
  namespace: flux-system
spec:
  ports:
  - name: http
    nodePort: 30080
    port: 9001
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: weave-gitops
    app.kubernetes.io/name: weave-gitops
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: weave-gitops
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: weave-gitops
    app.kubernetes.io/part-of: weave-gitops
    app.kubernetes.io/version: v0.39.1-rc.1
    helm.sh/chart: weave-gitops-0.39.1-rc.1
    weave.works/app: weave-gitops-oss
  name: weave-gitops
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: weave-gitops
      app.kubernetes.io/name: weave-gitops
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: weave-gitops
        app.kubernetes.io/name: weave-gitops
        app.kubernetes.io/part-of: weave-gitops
        weave.works/app: weave-gitops-oss
    spec:
      containers:
      - args:
        - --log-level
        - info
        - --insecure
        - --insecure-no-authentication-user=readonly-user
        env:
        - name: WEAVE_GITOPS_FEATURE_TENANCY
          value: 'true'
        - name: WEAVE_GITOPS_FEATURE_CLUSTER
          value: 'false'
        - name: WEAVE_GITOPS_FEATURE_GITOPS_RUNTIME
          value: 'false'
        image: ghcr.io/weaveworks/wego-app:v0.39.1-rc.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: http
        name: weave-gitops
        ports:
        - containerPort: 9001
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
      serviceAccountName: weave-gitops
---
# Read-only ClusterRole for anonymous access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: weave-gitops-readonly
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods", "pods/log", "events", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: ["gitrepositories", "helmrepositories", "helmcharts", "ocirepositories", "buckets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: ["kustomizations"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: ["helmreleases"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: weave-gitops-readonly-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: weave-gitops-readonly
subjects:
  - kind: User
    name: readonly-user
    apiGroup: rbac.authorization.k8s.io
