---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: weave-gitops
      version: "4.0.36"  # Chart version for app v0.38.0
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
  values:
    # Admin user - password: flux (bcrypt hash)
    adminUser:
      create: true
      username: admin
      # Password: flux (bcrypt)
      passwordHash: "$2a$10$P/tHQ1DNFXdvX0zRGA8LPeSOyb0JXq9rP3fZ4W8HGTpLV7qHDlWhe"
    # Service config
    service:
      type: NodePort
      port: 9001
      nodePort: 30080
